In [4]:
# SQL Analysis — Data Science Job Market

## This notebook uses SQL to analyze job postings, salaries,
## experience levels, work arrangements, company sizes, and locations.

In [5]:
import pandas as pd
import sqlite3

In [7]:
import os
print(os.getcwd())

/Users/apple

In [8]:
print(os.listdir("../"))

['apple', '.localized', 'Shared']

In [9]:
import os

print(os.listdir("/Users/Apple"))

['.config', 'Music', '.condarc', 'Untitled1.ipynb', '.DS_Store', '.CFUserTextEncoding', '.xonshrc', 'anaconda_projects', 'Untitled.ipynb', '01_job_market_analysis.ipynb', '.zshrc', 'OneDrive', 'Pictures', 'final_dataset.csv', 'Processed_Data.csv', '.zsh_history', '.ipython', 'Desktop', 'Library', '.matplotlib', '.lesshst', 'Public', 'Customer churn prediction', '.tcshrc', '.virtual_documents', '.anaconda', 'Movies', '.Trash', '.ipynb_checkpoints', '.jupyter', '.keras', 'Documents', '.bash_profile', 'anaconda3', 'Downloads', '.continuum', '.zsh_sessions', 'DataScience_salaries_2025.csv', '.conda', '02_sql_analysis.ipynb']

In [11]:
import os

print(os.listdir("/Users/Apple/OneDrive/Data science job market analytics"))

['.DS_Store', 'final_dataset.csv', 'Processed_Dataset.csv', 'DataScience_salaries_2025.json', 'Raw_dataset.csv']

In [14]:
df = pd.read_csv(
    "/Users/Apple/OneDrive/Data science job market analytics/final_dataset.csv"
)

In [15]:
df.shape

(46637, 15)

In [16]:
conn=sqlite3.connect("/Users/Apple/OneDrive/Data science job market analytics/job_market.db")

In [17]:
df.to_sql(
    "jobs",
    conn,
    if_exists="replace",
    index=False
)

46637

In [18]:
pd.read_sql(
    "SELECT COUNT(*) AS total_jobs FROM jobs;",
    conn
)

   total_jobs
0       46637

In [19]:
query = """
SELECT
    ROUND(AVG(salary_in_usd), 2) AS average_salary,
    MIN(salary_in_usd) AS minimum_salary,
    MAX(salary_in_usd) AS maximum_salary
FROM jobs;
"""

pd.read_sql(query, conn)

   average_salary  minimum_salary  maximum_salary
0       151411.82           15000          800000

In [20]:
query = """
SELECT
    job_title,
    COUNT(*) AS job_count
FROM jobs
GROUP BY job_title
ORDER BY job_count DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                   job_title  job_count
0             Data Scientist       5392
1              Data Engineer       5134
2               Data Analyst       4570
3          Software Engineer       3172
4                   Engineer       2712
5  Machine Learning Engineer       2688
6                    Manager       2171
7                    Analyst       1439
8         Research Scientist       1074
9         Analytics Engineer        947

In [21]:
query = """
SELECT
    experience_level_name,
    COUNT(*) AS job_count,
    ROUND(AVG(salary_in_usd), 2) AS average_salary
FROM jobs
GROUP BY experience_level_name
ORDER BY average_salary;
"""

pd.read_sql(query, conn)

  experience_level_name  job_count  average_salary
0                 Entry       5391        97693.09
1                   Mid      15049       137819.48
2                Senior      24749       168514.61
3             Executive       1448       200356.40

In [22]:
query = """
SELECT
    work_arrangement,
    COUNT(*) AS job_count,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM jobs),
        2
    ) AS percentage
FROM jobs
GROUP BY work_arrangement
ORDER BY job_count DESC;
"""

pd.read_sql(query, conn)

  work_arrangement  job_count  percentage
0          On-site      34848       74.72
1     Fully Remote      11493       24.64
2           Hybrid        296        0.63

In [23]:
query = """
SELECT
    company_size_name,
    COUNT(*) AS job_count,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM jobs),
        2
    ) AS percentage
FROM jobs
GROUP BY company_size_name
ORDER BY job_count DESC;
"""

pd.read_sql(query, conn)

  company_size_name  job_count  percentage
0            Medium      45117       96.74
1             Large       1310        2.81
2             Small        210        0.45

In [24]:
query = """
SELECT
    company_location,
    COUNT(*) AS job_count,
    ROUND(AVG(salary_in_usd), 2) AS average_salary
FROM jobs
GROUP BY company_location
ORDER BY job_count DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  company_location  job_count  average_salary
0               US      39512       159799.84
1               CA       2634       131132.48
2               GB       1875        98999.11
3               AU        283       127338.50
4               DE        245       101174.32
5               FR        186        79880.55
6               LT        181        61349.91
7               NL        174        79440.14
8               ES        140        71010.31
9               IN        121        55698.05

In [25]:
query = """
SELECT
    job_title,
    COUNT(*) AS job_count,
    ROUND(AVG(salary_in_usd), 2) AS average_salary
FROM jobs
GROUP BY job_title
HAVING COUNT(*) >= 50
ORDER BY average_salary DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                   job_title  job_count  average_salary
0        Engineering Manager        315       251996.19
1               Head of Data        166       220591.67
2               AI Architect        125       217205.30
3          Research Engineer        666       196898.35
4         Research Scientist       1074       194780.12
5                  Architect        210       191702.10
6          Applied Scientist        434       191614.49
7  Member of Technical Staff         51       189945.10
8            Product Manager        805       188948.91
9           Product Designer         57       188464.44

In [26]:
query = """
SELECT
    salary_category,
    COUNT(*) AS job_count,
    ROUND(AVG(salary_in_usd), 2) AS average_salary,
    ROUND(
        COUNT(*) * 100.0 / (SELECT COUNT(*) FROM jobs),
        2
    ) AS percentage
FROM jobs
GROUP BY salary_category
ORDER BY average_salary;
"""

pd.read_sql(query, conn)

  salary_category  job_count  average_salary  percentage
0     Below $100K      12511        72030.25       26.83
1     $100K-$200K      23728       144892.23       50.88
2     Above $200K      10398       261802.25       22.30

In [27]:
query = """
SELECT
    work_year,
    COUNT(*) AS job_count,
    ROUND(AVG(salary_in_usd), 2) AS average_salary,
    ROUND(MIN(salary_in_usd), 2) AS minimum_salary,
    ROUND(MAX(salary_in_usd), 2) AS maximum_salary
FROM jobs
GROUP BY work_year
ORDER BY work_year;
"""

pd.read_sql(query, conn)

   work_year  job_count  average_salary  minimum_salary  maximum_salary
0       2020         75       102250.87         15000.0        450000.0
1       2021        214        99309.71         15000.0        423000.0
2       2022       1113       131118.62         15000.0        430967.0
3       2023       4536       150117.90         15680.0        750000.0
4       2024      27686       152311.59         15107.0        800000.0
5       2025      13013       152824.36         15157.0        793136.0

In [28]:
query = """
SELECT
    experience_level_name,
    job_title,
    COUNT(*) AS job_count,
    ROUND(AVG(salary_in_usd), 2) AS average_salary
FROM jobs
GROUP BY experience_level_name, job_title
HAVING COUNT(*) >= 50
ORDER BY experience_level_name, average_salary DESC;
"""

pd.read_sql(query, conn).head(20)

,experience_level_name,job_title,job_count,average_salary
0,Entry,Research Scientist,119,175744.13
1,Entry,Research Engineer,66,141764.97
2,Entry,Machine Learning Engineer,149,133182.21
3,Entry,Software Engineer,196,117868.60
4,Entry,Engineer,219,102587.45
5,Entry,Business Intelligence Analyst,158,101416.41
6,Entry,Business Analyst,75,98565.81
7,Entry,Research Analyst,140,97056.79
8,Entry,Data Scientist,401,96084.01
9,Entry,Analyst,495,95899.33
10,Entry,Data Engineer,317,92457.62
11,Entry,Data Analyst,1726,90479.89
12,Entry,Data Management Analyst,77,89626.03
13,Entry,Data Quality Analyst,51,81325.84
14,Entry,Data Specialist,64,63967.25
15,Executive,Engineer,143,251674.07
16,Executive,Software Engineer,60,229009.45
17,Executive,Head of Data,147,228311.27
18,Executive,Data Engineer,264,204642.73
19,Executive,Data Scientist,156,199366.21

In [ ]:
s